[package]
name = "serial_int"
description = "Safe, immutable auto-increment integers"
version = "0.1.0"
authors = ["Jeff Anderson"]
edition = "2018"
repository = "https://git.sr.ht/~jeffa/serial_int"
license = "MIT"
