[package]
name = "serial_int"
description = "Safe, easy-to-use auto-increment integers"
version = "0.1.0"
authors = ["Jeff Anderson"]
edition = "2018"
repository = "https://git.sr.ht/~jeffa/serial_int"
license = "MIT"

[dependencies]
lazy_static = { version = "*", optional = true }

[features]
static_generator_u8 = []
static_generator_u16 = []
static_generator_u32 = []
static_generator_u64 = []
static_generator_usize = []
